=== evs38/trustedbird/ximfmail/chrome/content/theme/ximf.xsd
<?xml version="1.0" encoding="utf-8"?>
<!-- Created with Liquid XML Studio 1.0.8.0 (http://www.liquid-technologies.com) -->

<!-- ***** BEGIN LICENSE BLOCK *****
   - Copyright (c) 2008-2009 EADS DEFENCE AND SECURITY - All rights reserved.
   - ximfmail is under the triple license  MPL 1.1/GPL 2.0/LGPL 2.1.
   - 
   -
   - Redistribution and use, in source and binary forms, with or without modification, 
   - are permitted provided that the following conditons are met :
   -
   - 1. Redistributions of source code must retain the above copyright notice, 
   - 2. MPL 1.1/GPL 2.0/LGPL 2.1. license agreements must be attached 
   -    in the redistribution of the source code.
   - 3. Neither the names of the copyright holders nor the names of any contributors 
   -    may be used to endorse or promote products derived from this software without specific 
   -    prior written permission from EADS Defence and Security.
   - 
   - Alternatively, the contents of this file may be used under the terms of
   - either of the GNU General Public License Version 2 or later (the "GPL"),
   - or the GNU Lesser General Public License Version 2.1 or later (the "LGPL"),
   - in which case the provisions of the GPL or the LGPL are applicable instead
   - of those above. If you wish to allow use of your version of this file only
   - under the terms of either the GPL or the LGPL, and not to allow others to
   - use your version of this file under the terms of the MPL, indicate your
   - decision by deleting the provisions above and replace them with the notice
   - and other provisions required by the GPL or the LGPL. If you do not delete
   - the provisions above, a recipient may use your version of this file under
   - the terms of any one of the MPL, the GPL or the LGPL.
   - 
   - REMINDER  :
   - THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND 
   - ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED 
   - WARRANTIES OF MERCHANTABILITY AND FITNESS FOR  A PARTICULAR PURPOSE ARE DISCLAIMED. 
   - IN NO EVENT SHALL THE COPYRIGHT HOLDERS OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, 
   - INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES 
   - (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; 
   - LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, 
   - WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING 
   - IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
   -  
   - EADS Defence and Security - 1 Boulevard Jean Moulin -  
   - ZAC de la Clef Saint Pierre - 78990 Elancourt - FRANCE (IDDN.FR.001.480012.002.S.P.2008.000.10000) 
   - ***** END LICENSE BLOCK ***** -->
<xs:schema elementFormDefault="qualified" targetNamespace="http://eads.org/ximf/" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:annotation>
    <xs:documentation> $Header: /data/cvs/v1/MCO2008/mozilla/extensions/ximf/ximfmail/chrome/content/theme/ximf.xsd,v 1.1 2008/11/25 18:51:12 xparis Exp $ </xs:documentation>
  </xs:annotation>
  <xs:element name="instance">
    <xs:complexType>
      <xs:complexContent mixed="false">
        <xs:extension xmlns:q1="http://eads.org/ximf/" base="q1:XIMFInstanceType" />
      </xs:complexContent>
    </xs:complexType>
  </xs:element>
  <xs:complexType name="XIMFInstanceType">
    <xs:sequence minOccurs="0">
      <xs:element xmlns:q1="http://eads.org/ximf/" minOccurs="0" maxOccurs="unbounded" name="header" type="q1:XIMFHeaderType" />
      <xs:element xmlns:q2="http://eads.org/ximf/" minOccurs="0" maxOccurs="unbounded" name="rule" type="q2:XIMFRuleType" />
      <xs:element minOccurs="0" maxOccurs="unbounded" name="dictionary" xmlns:q1="http://eads.org/ximf/" type="q1:XIMFDictionaryType" />
    </xs:sequence>
    <xs:attribute name="ximfVersion" use="required">
      <xs:simpleType>
        <xs:restriction base="xs:string">
          <xs:enumeration value="2.0" />
        </xs:restriction>
      </xs:simpleType>
    </xs:attribute>
    <xs:attribute name="version" type="xs:string" use="required" />
    <xs:attribute name="author" type="xs:string" />
    <xs:attribute name="creationDate" type="xs:date" />
    <xs:attribute name="name" type="xs:string" use="required" />
  </xs:complexType>
  <xs:complexType name="XIMFHeaderType">
    <xs:choice minOccurs="1" maxOccurs="1">
      <xs:element xmlns:q1="http://eads.org/ximf/" minOccurs="1" maxOccurs="unbounded" name="set" type="q1:XIMFSetType" />
      <xs:element xmlns:q1="http://eads.org/ximf/" minOccurs="1" maxOccurs="unbounded" name="multiset" type="q1:XIMFMultiSetType" />
      <xs:element minOccurs="0" maxOccurs="unbounded" name="compstring" xmlns:q2="http://eads.org/ximf/" type="q2:XIMFComplexString" />
      <xs:element xmlns:q7="http://eads.org/ximf/" minOccurs="1" maxOccurs="1" name="string" type="q7:XIMFPrintableStringDataType" />
    </xs:choice>
    <xs:attribute xmlns:q1="http://eads.org/ximf/" name="id" type="q1:XIMFHeaderID" use="required" />
    <xs:attribute xmlns:q2="http://eads.org/ximf/" name="headerName" type="q2:XIMFPrintableStringType" use="required" />
    <xs:attribute xmlns:q1="http://eads.org/ximf/" name="technicalHeaderName" type="q1:XIMFPrintableStringType" use="optional" />
    <xs:attribute name="type" type="xs:string" use="required" />
    <xs:attribute name="technicalType" type="xs:string" use="optional" />
    <xs:attribute name="isMandatory" type="xs:boolean" use="required" />
    <xs:attribute name="ilk" type="xs:string" use="optional" />
    <xs:attribute xmlns:q2="http://eads.org/ximf/" name="description" type="xs:string" use="optional" />
  </xs:complexType>
  <xs:complexType name="XIMFSetType">
    <xs:choice minOccurs="0" maxOccurs="unbounded">
      <xs:element xmlns:q7="http://eads.org/ximf/" name="string" type="q7:XIMFPrintableStringDataType" />
      <xs:element xmlns:q1="http://eads.org/ximf/" minOccurs="1" maxOccurs="1" name="compstring" type="q1:XIMFComplexString" />
    </xs:choice>
    <xs:attributeGroup xmlns:q2="http://eads.org/ximf/" ref="q2:XIMFFacetsGroup" />
    <xs:attributeGroup xmlns:q3="http://eads.org/ximf/" ref="q3:XIMFPropertiesGroup" />
  </xs:complexType>
  <xs:complexType name="XIMFMultiSetType">
    <xs:choice minOccurs="0" maxOccurs="unbounded">
      <xs:element xmlns:q7="http://eads.org/ximf/" name="string" type="q7:XIMFPrintableStringDataType" />
      <xs:element xmlns:q1="http://eads.org/ximf/" minOccurs="1" maxOccurs="1" name="compstring" type="q1:XIMFComplexString" />
    </xs:choice>
    <xs:attributeGroup xmlns:q4="http://eads.org/ximf/" ref="q4:XIMFFacetsGroup" />
    <xs:attributeGroup xmlns:q5="http://eads.org/ximf/" ref="q5:XIMFPropertiesGroup" />
  </xs:complexType>
  <xs:complexType name="XIMFSequenceType">
    <xs:choice minOccurs="2" maxOccurs="unbounded">
      <xs:element xmlns:q6="http://eads.org/ximf/" name="set" type="q6:XIMFSetType" />
      <xs:element xmlns:q7="http://eads.org/ximf/" name="multiset" type="q7:XIMFMultiSetType" />
      <xs:element xmlns:q8="http://eads.org/ximf/" name="string" type="q8:XIMFPrintableStringDataType" />
    </xs:choice>
    <xs:attributeGroup xmlns:q9="http://eads.org/ximf/" ref="q9:XIMFFacetsGroup" />
    <xs:attributeGroup xmlns:q10="http://eads.org/ximf/" ref="q10:XIMFPropertiesGroup" />
    <xs:attribute default="false" name="reverse" type="xs:boolean" />
    <xs:attribute default="false" name="technicalReverse" type="xs:boolean" />
  </xs:complexType>
  <xs:complexType name="XIMFPrintableStringDataType">
    <xs:sequence>
      <xs:element xmlns:q2="http://eads.org/ximf/" minOccurs="0" maxOccurs="unbounded" name="linkedValue" type="q2:XIMFLinkedValue" />
    </xs:sequence>
    <xs:attributeGroup xmlns:q11="http://eads.org/ximf/" ref="q11:XIMFFacetsGroup" />
    <xs:attributeGroup xmlns:q12="http://eads.org/ximf/" ref="q12:XIMFPropertiesGroup" />
    <xs:attribute default="false" name="editable" type="xs:boolean" use="optional" />
    <xs:attributeGroup xmlns:q3="http://eads.org/ximf/" ref="q3:XIMFContentGroup" />
  </xs:complexType>
  <xs:complexType name="XIMFLinkedValue">
    <xs:attribute name="ref" type="xs:IDREF" use="required" />
  </xs:complexType>
  <xs:complexType name="XIMFRuleType">
    <xs:choice minOccurs="1" maxOccurs="1">
      <xs:sequence minOccurs="1" maxOccurs="unbounded">
        <xs:element xmlns:q3="http://eads.org/ximf/" name="constraint" type="q3:XIMFConstraintType" />
      </xs:sequence>
      <xs:sequence minOccurs="1" maxOccurs="unbounded">
        <xs:element xmlns:q1="http://eads.org/ximf/" name="processing" type="q1:XIMFProcessingType" />
      </xs:sequence>
      <xs:sequence minOccurs="1" maxOccurs="unbounded">
        <xs:element xmlns:q4="http://eads.org/ximf/" name="compatibility" type="q4:XIMFCompatibilityType" />
      </xs:sequence>
      <xs:sequence minOccurs="1" maxOccurs="unbounded">
        <xs:element xmlns:q5="http://eads.org/ximf/" name="policy" type="q5:XIMFPolicyType" />
      </xs:sequence>
      <xs:sequence minOccurs="1" maxOccurs="unbounded">
        <xs:element xmlns:q2="http://eads.org/ximf/" name="custom" type="q2:XIMFCustomType" />
      </xs:sequence>
    </xs:choice>
    <xs:attribute name="agent" use="optional">
      <xs:simpleType>
        <xs:restriction base="xs:string">
          <xs:enumeration value="mua" />
          <xs:enumeration value="mta" />
          <xs:enumeration value="mda" />
          <xs:enumeration value="msa" />
          <xs:enumeration value="gateway" />
        </xs:restriction>
      </xs:simpleType>
    </xs:attribute>
    <xs:attribute name="id" type="xs:ID" use="required" />
    <xs:attribute name="description" type="xs:string" use="optional" />
  </xs:complexType>
  <xs:complexType name="XIMFConstraintType">
    <xs:attribute xmlns:q5="http://eads.org/ximf/" name="left" type="q5:XIMFHeaderRef" use="required" />
    <xs:attribute name="operator" use="required">
      <xs:simpleType>
        <xs:restriction base="xs:string">
          <xs:enumeration value="greaterThan" />
          <xs:enumeration value="lowerThan" />
          <xs:enumeration value="equalOrGreaterThan" />
          <xs:enumeration value="equalOrLowerThan" />
          <xs:enumeration value="equal" />
        </xs:restriction>
      </xs:simpleType>
    </xs:attribute>
    <xs:attribute name="right" type="xs:IDREF" use="required" />
  </xs:complexType>
  <xs:complexType name="XIMFProcessingType">
    <xs:sequence minOccurs="1" maxOccurs="unbounded">
      <xs:element xmlns:q2="http://eads.org/ximf/" name="headerName" type="q2:XIMFPrintableStringType" />
    </xs:sequence>
    <xs:attribute name="type">
      <xs:simpleType>
        <xs:restriction base="xs:string">
          <xs:enumeration value="sign-header-value" />
          <xs:enumeration value="encrypt-header-value" />
          <xs:enumeration value="capitalize-header-value" />
        </xs:restriction>
      </xs:simpleType>
    </xs:attribute>
  </xs:complexType>
  <xs:complexType name="XIMFCompatibilityType">
    <xs:sequence maxOccurs="unbounded">
      <xs:element xmlns:q5="http://eads.org/ximf/" minOccurs="1" maxOccurs="unbounded" name="aliasHeader">
        <xs:complexType>
          <xs:complexContent mixed="false">
            <xs:extension base="q5:XIMFHeaderAliasType">
              <xs:sequence minOccurs="0" maxOccurs="unbounded">
                <xs:element name="aliasValue">
                  <xs:complexType>
                    <xs:complexContent mixed="false">
                      <xs:extension base="q5:XIMFValueAliasType" />
                    </xs:complexContent>
                  </xs:complexType>
                </xs:element>
              </xs:sequence>
            </xs:extension>
          </xs:complexContent>
        </xs:complexType>
      </xs:element>
    </xs:sequence>
    <xs:attribute name="targetName" type="xs:string" use="required" />
    <xs:attribute name="targetVersion" type="xs:string" use="required" />
  </xs:complexType>
  <xs:complexType name="XIMFHeaderAliasType">
    <xs:attribute xmlns:q3="http://eads.org/ximf/" name="headerName" type="q3:XIMFPrintableStringType" use="required" />
    <xs:attribute xmlns:q4="http://eads.org/ximf/" name="headerRef" type="q4:XIMFPrintableStringType" use="optional" />
  </xs:complexType>
  <xs:complexType name="XIMFValueAliasType">
    <xs:attribute xmlns:q5="http://eads.org/ximf/" name="valueName" type="q5:XIMFPrintableStringType" use="required" />
    <xs:attribute xmlns:q6="http://eads.org/ximf/" name="valueRef" type="q6:XIMFPrintableStringType" use="optional" />
  </xs:complexType>
  <xs:complexType name="XIMFPolicyType">
    <xs:sequence minOccurs="1" maxOccurs="unbounded">
      <xs:element xmlns:q5="http://eads.org/ximf/" name="role">
        <xs:complexType>
          <xs:complexContent mixed="false">
            <xs:extension base="q5:XIMFACLRoleType" />
          </xs:complexContent>
        </xs:complexType>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="XIMFACLRoleType">
    <xs:attribute name="aclLevel" type="xs:unsignedInt" />
    <xs:attribute name="id" type="xs:ID" use="optional" />
  </xs:complexType>
  <xs:complexType name="XIMFCustomType">
    <xs:choice>
      <xs:any maxOccurs="unbounded" processContents="skip" />
    </xs:choice>
    <xs:attribute name="id" type="xs:ID" use="required" />
    <xs:attribute name="provider" type="xs:string" use="required" />
    <xs:attribute name="description" type="xs:string" use="optional" />
  </xs:complexType>
  <xs:simpleType name="XIMFPrintableStringType">
    <xs:restriction base="xs:string">
      <xs:pattern value="([A-Za-z0-9]|[ ,;:=/\?'\(\)\+\-\.])+" />
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="XIMFOidType">
    <xs:restriction base="xs:string">
      <xs:pattern value="([0-9]|([1-9][0-9]+))(\.([0-9]|([1-9][0-9]+)))+" />
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="XIMFHeaderID">
    <xs:restriction base="xs:ID">
      <xs:pattern value="header\-.*" />
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="XIMFHeaderRef">
    <xs:restriction base="xs:IDREF">
      <xs:pattern value="header\-.*" />
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="XIMFValueID">
    <xs:restriction base="xs:ID">
      <xs:pattern value="value\-.*" />
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="XIMFValueRef">
    <xs:restriction base="xs:IDREF">
      <xs:pattern value="value\-.*" />
    </xs:restriction>
  </xs:simpleType>
  <xs:complexType name="XIMFComplexString">
    <xs:choice minOccurs="0">
      <xs:element xmlns:q1="http://eads.org/ximf/" minOccurs="0" name="string" type="q1:XIMFPrintableStringDataType" />
      <xs:element xmlns:q2="http://eads.org/ximf/" minOccurs="0" name="set" type="q2:XIMFSetType" />
      <xs:element xmlns:q3="http://eads.org/ximf/" minOccurs="0" name="multiset" type="q3:XIMFMultiSetType" />
      <xs:element xmlns:q4="http://eads.org/ximf/" minOccurs="0" maxOccurs="unbounded" name="compstring" type="q4:XIMFComplexString" />
    </xs:choice>
    <xs:attributeGroup xmlns:q5="http://eads.org/ximf/" ref="q5:XIMFPropertiesGroup" />
    <xs:attributeGroup xmlns:q4="http://eads.org/ximf/" ref="q4:XIMFFacetsGroup" />
    <xs:attributeGroup xmlns:q5="http://eads.org/ximf/" ref="q5:XIMFContentGroup" />
    <xs:attribute name="contentPositionEnd" type="xs:boolean" />
    <xs:attribute name="contentFactorise" type="xs:boolean" />
    <xs:attribute name="technicalPositionEnd" type="xs:boolean" />
  </xs:complexType>
  <xs:complexType name="XIMFDictionaryType">
    <xs:choice maxOccurs="unbounded">
      <xs:element name="locale">
        <xs:complexType>
          <xs:complexContent mixed="false">
            <xs:extension xmlns:q14="http://eads.org/ximf/" base="q14:XIMFLocaleType" />
          </xs:complexContent>
        </xs:complexType>
      </xs:element>
    </xs:choice>
  </xs:complexType>
  <xs:complexType name="XIMFLocaleType">
    <xs:choice maxOccurs="unbounded">
      <xs:element name="locale" xmlns:q6="http://eads.org/ximf/" type="q6:XIMFIlkType" />
    </xs:choice>
    <xs:attribute name="lang" type="xs:string" use="required" />
    <xs:attribute name="country" use="optional" />
  </xs:complexType>
  <xs:complexType name="XIMFIlkType">
    <xs:choice maxOccurs="unbounded">
      <xs:element name="ilk">
        <xs:complexType>
          <xs:simpleContent>
            <xs:extension base="xs:string">
              <xs:attribute name="entity" type="xs:string" use="required" />
            </xs:extension>
          </xs:simpleContent>
        </xs:complexType>
      </xs:element>
    </xs:choice>
  </xs:complexType>
  <xs:attributeGroup name="XIMFContentGroup">
    <xs:attribute name="content" xmlns:q7="http://eads.org/ximf/" type="q7:XIMFPrintableStringType" />
    <xs:attribute xmlns:q3="http://eads.org/ximf/" name="technicalContent" type="q3:XIMFPrintableStringType" use="optional" />
  </xs:attributeGroup>
  <xs:attributeGroup name="XIMFPropertiesGroup">
    <xs:attribute xmlns:q3="http://eads.org/ximf/" name="id" type="q3:XIMFValueID" use="optional" />
    <xs:attribute xmlns:q4="http://eads.org/ximf/" name="ref" type="q4:XIMFValueRef" use="optional" />
    <xs:attribute name="ilk" type="xs:string" use="optional" />
    <xs:attribute name="aclLevel" type="xs:unsignedInt" use="optional" />
    <xs:attribute name="index" type="xs:unsignedInt" use="optional" />
    <xs:attribute xmlns:q4="http://eads.org/ximf/" name="description" type="xs:string" use="optional" />
  </xs:attributeGroup>
  <xs:attributeGroup name="XIMFFacetsGroup">
    <xs:attribute name="maxLength" type="xs:unsignedInt" use="optional" />
    <xs:attribute name="minLength" type="xs:unsignedInt" use="optional" />
    <xs:attribute default="1" name="maxItem" type="xs:unsignedInt" use="optional" />
    <xs:attribute name="minItem" type="xs:unsignedInt" use="optional" />
    <xs:attribute xmlns:q15="http://eads.org/ximf/" name="separator" type="q15:XIMFPrintableStringType" use="optional" />
    <xs:attribute xmlns:q16="http://eads.org/ximf/" name="technicalSeparator" type="q16:XIMFPrintableStringType" use="optional" />
  </xs:attributeGroup>
</xs:schema>

=== evs38/trustedbird/ximfmail-company/chrome/content/WhirlpoolCorporation/headers-whirlpool.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="ximftoxul.xsl"?>
<ximf:instance name="Whirlpool" version="1.0" ximfVersion="2.0" xmlns:ximf="http://eads.org/ximf/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://eads.org/ximf/ ximf.xsd">

	<!--  OID WHIRLPOOL -->
	<ximf:header id="header-policy-identifier" headerName="X-XIMF-Security-Policy-Identifier" >		
		<ximf:string content="1.2.840.113549.1.9.16.7.3"/>
	</ximf:header>
	
	<!-- Security Classification-->
	<ximf:header id="header-classification" 
				 headerName="X-XIMF-Security-Classification"
				 technicalHeaderName="X-XIMF-Security-Classification-Identifier"
				 type="string"
				 technicalType="oid"
				 ilk="ilk-classification"
				 isMandatory="true">
		<ximf:set id="value-whirlpool-classification">
			<ximf:string ilk="ilk-public" content="whirlpool-public" technicalContent="6" >	
				<ximf:linkedValue ref="value-privacy-mark-other" />
			</ximf:string>						
			<ximf:string ilk="ilk-internal" content="whirlpool-internal" technicalContent="7" >
				<ximf:linkedValue ref="value-privacy-mark-confidential" />
			</ximf:string>			
			<ximf:string ilk="ilk-confidential" content="whirlpool-confidential" technicalContent="8" >
				<ximf:linkedValue ref="value-privacy-mark-confidential" />
			</ximf:string>				
		</ximf:set>
	</ximf:header>	
	<ximf:header id="header-privacy-mark" headerName="X-XIMF-Privacy-Mark" ilk="ilk-privacy-mark" isMandatory="false">
		<ximf:set id="value-privacy-mark-confidential">
			<ximf:string ilk="MAKE NO COPY" content="MAKE NO COPY" />
			<ximf:string ilk="ATTORNEY-CLIENT PRIVILEGED DOCUMENT" content="ATTORNEY-CLIENT PRIVILEGED DOCUMENT" />
			<ximf:string ilk="THIRD PARTY CONFIDENTIAL" content="THIRD PARTY CONFIDENTIAL" />
			<ximf:compstring ilk="LIMITED TO" content="LIMITED TO" separator=" : ">
				<ximf:string editable="true" />
			</ximf:compstring>
			<ximf:string ilk="COVERED BY A NON-ANALYSIS AGREEMENT" content="COVERED BY A NON-ANALYSIS AGREEMENT" />
		</ximf:set>
		<ximf:set id="value-privacy-mark-other">
			<ximf:string ilk="SEND BY INTERNET" content="SEND BY INTERNET" />
			<ximf:string ilk="PRIVATE" content="PRIVATE" />
		</ximf:set>
	</ximf:header>
	
	<!-- headers unmandatories -->
	<ximf:header id="header-reply-before" headerName="X-XIMF-Reply-Before" ilk="ilk-reply-before" isMandatory="false" type="date">
		<ximf:string id="value-reply-before" editable="true" />
	</ximf:header>	
	
	<ximf:header id="header-originator-reference" headerName="X-XIMF-Originator-Reference" ilk="ilk-originator-reference" isMandatory="false" type="string">
		<ximf:string id="value-originator-reference" maxItem="10" editable="true" separator=" - "/>
	</ximf:header>
	
	<!-- Adresses exemptÃ©es -->
	<ximf:header id="header-exempted-address" headerName="X-XIMF-Exempted-Address" ilk="ilk-exempted-address" isMandatory="false" type="address">
		<ximf:string id="value-exempted-address" editable="true" />
	</ximf:header>

</ximf:instance>

=== evs38/trustedbird/contributor/airbusdefenceandspace/addons/ximf_company_def/chrome/content/CaterpillarInc/rules-caterpillar.xml
<?xml version="1.0" encoding="UTF-8"?>

<ximf:instance name="caterpillar" version="1.0" ximfVersion="2.0" xmlns:ximf="http://eads.org/ximf/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://eads.org/ximf/ ximf.xsd">
	<ximf:rule id="compatibility-rule" description="Règle sur la compatibilités X-SMTP / XIMF" >
		<ximf:association>
				<ximf:aliasHeader headerName="X-XIMF-Copy-Precedence" headerRef="X-XIMF-Primary-Precedence">				
				<ximf:aliasValue valueName="routine" valueRef="routine" />
				<ximf:aliasValue valueName="routine" valueRef="priority" />
				<ximf:aliasValue valueName="routine,priority" valueRef="immediate" />
				<ximf:aliasValue valueName="routine,priority,immediate" valueRef="flash" />
				</ximf:aliasHeader>
		</ximf:association>
	</ximf:rule>
	<ximf:rule id="label-pictures-rule" description="rule to display pictures on received mails" >	
		<ximf:classificationPictures targetName="ClassificationPictures">
			<ximf:aliasHeader headerName="url" headerRef="X-XIMF-Security-Classification-Identifier" >					
				<ximf:aliasValue valueRef="7" valueName="chrome://ximf-conpany-def/content/CaterpillarInc/resource/caterpillar-green.png" />
				<ximf:aliasValue valueRef="8" valueName="chrome://ximf-conpany-def/content/CaterpillarInc/resource/caterpillar-yellow.png" />
				<ximf:aliasValue valueRef="9" valueName="chrome://ximf-conpany-def/content/CaterpillarInc/resource/caterpillar-red.png" />				
			</ximf:aliasHeader>
		</ximf:classificationPictures>		
	</ximf:rule>
</ximf:instance>

=== evs38/trustedbird/old/TestXimf/mozilla/extensions/ximf/ximf_company_def/chrome/content/WhirlpoolCorporation/dictionary-whirlpool.xml
<?xml version="1.0" encoding="UTF-8"?>

<ximf:instance name="Whirlpool" version="1.0" ximfVersion="2.0" xmlns:ximf="http://eads.org/ximf/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://eads.org/ximf/ ximf.xsd">
	<ximf:dictionary id="OneDico">
		<ximf:locale lang="fr-FR">
			<ximf:ilk entity="ilk-exempted-address">Adresses exemptées</ximf:ilk>
			<ximf:ilk entity="ilk-address">Addresses</ximf:ilk>
			<ximf:ilk entity="ilk-urgence-box">Information</ximf:ilk>
			<ximf:ilk entity="ilk-general-panel">Général</ximf:ilk>
			<ximf:ilk entity="ilk-internal">INTERNE</ximf:ilk>
			<ximf:ilk entity="ilk-public">PUBLIC</ximf:ilk>
			<ximf:ilk entity="ilk-security-panel">Securité</ximf:ilk>
			<ximf:ilk entity="ilk-originator-reference">Réferences d'origine</ximf:ilk>	
			<ximf:ilk entity="ilk-reply-before">Répondre avant</ximf:ilk>
			<ximf:ilk entity="ilk-classification-panel">Classification</ximf:ilk>
			<ximf:ilk entity="ilk-classification">Classification de sécurité</ximf:ilk>
			<ximf:ilk entity="ilk-privacy-mark">Marque privée</ximf:ilk>			
			<ximf:ilk entity="ilk-general">Général</ximf:ilk>
			<ximf:ilk entity="ilk-confidential">CONFIDENTIEL</ximf:ilk>			
			<ximf:ilk entity="ilk-highly-confidential">Très confidentiel</ximf:ilk>
			<ximf:ilk entity="ilk-minimum">Minimum</ximf:ilk>
			<ximf:ilk entity="ilk-medium">Moyen</ximf:ilk>
			<ximf:ilk entity="ilk-maximum">Maximum</ximf:ilk>
			<ximf:ilk entity="ilk-critical">Critique</ximf:ilk>			
		</ximf:locale>
		<ximf:locale lang="en-US">
			<ximf:ilk entity="ilk-exempted-address">Exempted adresses</ximf:ilk>
			<ximf:ilk entity="ilk-address">Address</ximf:ilk>
			<ximf:ilk entity="ilk-urgence-box">Information</ximf:ilk>
			<ximf:ilk entity="ilk-general-panel">General</ximf:ilk>
			<ximf:ilk entity="ilk-internal">INTERAL</ximf:ilk>
			<ximf:ilk entity="ilk-public">PUBLIC</ximf:ilk>
			<ximf:ilk entity="ilk-security-panel">Security</ximf:ilk>
			<ximf:ilk entity="ilk-reply-before">Reply before</ximf:ilk>
			<ximf:ilk entity="ilk-originator-reference">Origin references</ximf:ilk>
			<ximf:ilk entity="ilk-classification-panel">Classification</ximf:ilk>
			<ximf:ilk entity="ilk-classification">Security classification</ximf:ilk>
			<ximf:ilk entity="ilk-privacy-mark">Privacy mark</ximf:ilk>
			<ximf:ilk entity="ilk-general">General</ximf:ilk>
			<ximf:ilk entity="ilk-confidential">CONFIDENTIAL</ximf:ilk>			
			<ximf:ilk entity="ilk-highly-confidential">Highly Confidential</ximf:ilk>
			<ximf:ilk entity="ilk-minimum">Minimum</ximf:ilk>
			<ximf:ilk entity="ilk-medium">Medium</ximf:ilk>
			<ximf:ilk entity="ilk-maximum">Maximum</ximf:ilk>
			<ximf:ilk entity="ilk-critical">Critical</ximf:ilk>			
		</ximf:locale>
	</ximf:dictionary>
</ximf:instance>

=== evs38/trustedbird/trustedbird-patch-source-dev/trustedbird-patch-source-3.1.4+0.3/comm-1.9.2/mozilla/extensions/ximf/ximf_company_def/chrome/content/AmocoCorporation/rules-amoco.xml
<?xml version="1.0" encoding="UTF-8"?>

<ximf:instance name="Amoco" version="1.0" ximfVersion="2.0" xmlns:ximf="http://eads.org/ximf/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://eads.org/ximf/ ximf.xsd">
	<ximf:rule id="compatibility-rule" description="Règle sur la compatibilités X-SMTP / XIMF" >
		<ximf:compatibility targetName="X-SMTP" targetVersion="1.1">
			<ximf:aliasHeader headerName="X-P772-Version">
				 <ximf:aliasValue valueName="1.1"/> 
			</ximf:aliasHeader>				
			<ximf:aliasHeader headerName="X-P772-Originator-Reference" headerRef="X-XIMF-Originator-Reference"/>
			<ximf:aliasHeader headerName="X-P772-Security-Classification" headerRef="X-XIMF-Security-Classification"/>
		</ximf:compatibility>		
	</ximf:rule>
	<ximf:rule id="association-rule" description="Règle d'associations de valeurs" >
		<ximf:association>
			<ximf:aliasHeader headerName="X-XIMF-Privacy-Mark" headerRef="X-XIMF-Security-Classification">
				<ximf:aliasValue valueName="amoco-minimum,amoco-medium" valueRef="amoco-general" />
				<ximf:aliasValue valueName="amoco-minimum,amoco-medium,amoco-maximum" valueRef="amoco-confidential" />
				<ximf:aliasValue valueName="amoco-minimum,amoco-medium,amoco-maximum,amoco-critical" valueRef="amoco-highly-confidential" />
			</ximf:aliasHeader>					
		</ximf:association>
	</ximf:rule>			
</ximf:instance>
